// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpfwM2ZANSqXsA4F-6sBbUxRIrP39wxg0',
    appId: '1:3474608081:web:2d940da98924e40c971af0',
    messagingSenderId: '3474608081',
    projectId: 'cnote-f2871',
    authDomain: 'cnote-f2871.firebaseapp.com',
    storageBucket: 'cnote-f2871.appspot.com',
    measurementId: 'G-JLPKKJH6PX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjK2Tz_OO5mYJXGkshN0ZAuhHV4RciuNo',
    appId: '1:3474608081:android:d35fac211999c09e971af0',
    messagingSenderId: '3474608081',
    projectId: 'cnote-f2871',
    storageBucket: 'cnote-f2871.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwyCpzwMuua33tZ_FPfw8c3yy42eJJo1M',
    appId: '1:3474608081:ios:0a358d732f5273cc971af0',
    messagingSenderId: '3474608081',
    projectId: 'cnote-f2871',
    storageBucket: 'cnote-f2871.appspot.com',
    androidClientId: '3474608081-ed2euu04701dtoijctlbc5d9kktvr5qv.apps.googleusercontent.com',
    iosClientId: '3474608081-9665vbqlef5bfk1hcvpjg5pvvvnm91sb.apps.googleusercontent.com',
    iosBundleId: 'com.cyclones.cnote',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwyCpzwMuua33tZ_FPfw8c3yy42eJJo1M',
    appId: '1:3474608081:ios:0a358d732f5273cc971af0',
    messagingSenderId: '3474608081',
    projectId: 'cnote-f2871',
    storageBucket: 'cnote-f2871.appspot.com',
    androidClientId: '3474608081-ed2euu04701dtoijctlbc5d9kktvr5qv.apps.googleusercontent.com',
    iosClientId: '3474608081-9665vbqlef5bfk1hcvpjg5pvvvnm91sb.apps.googleusercontent.com',
    iosBundleId: 'com.cyclones.cnote',
  );
}
